name: Integration

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]
jobs:
  build:
    name: Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npx ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:ci
